# Generated by Django 3.0.6 on 2020-07-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(help_text='請輸入icon名稱', max_length=30)),
                ('last_path', models.FileField(upload_to='')),
            ],
        ),
    ]
