# Generated by Django 3.0.6 on 2020-07-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taka_icons', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icon',
            options={'ordering': ['icon_name']},
        ),
        migrations.RenameField(
            model_name='icon',
            old_name='last_path',
            new_name='icon_file',
        ),
    ]
